# Generated by Django 3.0.2 on 2020-01-28 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobsData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('experience', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('skill_set', models.TextField()),
                ('salary', models.CharField(max_length=255)),
                ('posted_date', models.CharField(max_length=255)),
                ('job_url', models.TextField()),
                ('job_site', models.CharField(max_length=255)),
            ],
        ),
    ]
