# Generated by Django 3.0.2 on 2020-01-28 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_scrap', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobsdata',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='jobsdata',
            name='experience',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='jobsdata',
            name='job_site',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='jobsdata',
            name='job_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='jobsdata',
            name='job_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobsdata',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='jobsdata',
            name='posted_date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='jobsdata',
            name='salary',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='jobsdata',
            name='skill_set',
            field=models.TextField(blank=True, null=True),
        ),
    ]
